version: '3.7'

services:
  game_postgres:
    image: postgres:12.0-alpine
    environment:
       POSTGRES_USER: gameshare_app
       POSTGRES_PASSWORD: gameshare_dev_admin
       POSTGRES_DB: gameshare_dev_db
       PGDATA: /var/lib/postgresql/data/gameshare/
    volumes:
      - game_db_data:/var/lib/postgresql/data/gameshare:rw
    restart: unless-stopped
  web:
    build: .
    volumes:
      - .:/code:rw
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - game_postgres
    restart: unless-stopped

volumes:
  game_db_data: