# Generated by Django 3.2.6 on 2021-08-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('label', models.CharField(choices=[('TABLE', 'Table'), ('PC', 'Personal Computer'), ('X-BOX', 'X Box'), ('PS', 'Play Station')], default='TABLE', max_length=7)),
            ],
        ),
    ]
